"""Compatibility import for the Codex C2 compact-Q0 routine candidate."""

from agricola.strategy.codex_compact_q0 import (
    CODEX_COHORT_OFFSET,
    CODEX_CROP_PLAN,
    CODEX_CROP_POSITIONS,
    CODEX_CROP_ZONES,
    CODEX_PASTURE_POSITIONS,
    EMPTY_ASSIGNED,
    FOUNDATION_CHECKPOINT,
    GROWING,
    HARVEST_READY,
    LOST_WEED,
    MODEL_SPEC_VERSION,
    OUT_OF_SCOPE,
    RETIREMENT_DUE,
    YIELD_ACCUMULATING,
    CodexC2Agent,
    classify_tile_lifecycle,
    create_agent,
    lifespan_decay_started,
    load_candidate_config,
    plant_matches_cohort,
    water_loss_at_eod_if_unserved,
    yield_completion_water_due,
)

__all__ = [
    "CODEX_COHORT_OFFSET",
    "CODEX_CROP_PLAN",
    "CODEX_CROP_POSITIONS",
    "CODEX_CROP_ZONES",
    "CODEX_PASTURE_POSITIONS",
    "EMPTY_ASSIGNED",
    "FOUNDATION_CHECKPOINT",
    "GROWING",
    "HARVEST_READY",
    "LOST_WEED",
    "MODEL_SPEC_VERSION",
    "OUT_OF_SCOPE",
    "RETIREMENT_DUE",
    "YIELD_ACCUMULATING",
    "CodexC2Agent",
    "classify_tile_lifecycle",
    "create_agent",
    "lifespan_decay_started",
    "load_candidate_config",
    "plant_matches_cohort",
    "water_loss_at_eod_if_unserved",
    "yield_completion_water_due",
]
