"""Recurrence census within frozen top sample and interactive daily route atlas."""
import gzip,json,csv,html,statistics as st,itertools,sys
from pathlib import Path
from collections import Counter,defaultdict
ROOT=Path(__file__).resolve().parents[5];sys.path.insert(0,str(ROOT))
from docs.model_specs.codex.e22.tools.report_external_20260914 import CSS
OUT=ROOT/'docs/model_specs/codex/e22/reports/top_2750_3000_20260914'
def main():
 ps=[json.load(gzip.open(p,'rt',encoding='utf-8')) for p in sorted((OUT/'profiles').glob('*.gz'))];assert len(ps)==25
 protocol=json.loads((OUT/'PROTOCOL.json').read_text());summaries=[];recurrences=[];routecsv=[];atlas=[];pairwise=[];placementcsv=[]
 for spec in protocol['selections']:
  sid=spec['submission'];gs=[p for p in ps if p['meta']['submission']==sid];profiles=[g['profile'] for g in gs]
  signatures=Counter(json.dumps([(t['x'],t['y'],t['kind']) for t in p['maps'][-1] if t['kind'] in ['PASTURE','COOP']]) for p in profiles)
  mixes=Counter('/'.join(str(p['kpi'][-1][a]) for a in ['COW','SHEEP','GOOSE']) for p in profiles)
  sims=[]
  for a,b in itertools.combinations(gs,2):
   ca=a['profile']['commands'];cb=b['profile']['commands'];row=dict(submission=sid,episode_a=a['meta']['episode'],episode_b=b['meta']['episode'])
   for label,start,end in [('D1_11',0,264),('D12_19',264,456),('D20_30',456,719)]:
    n=sum([x.get('farmer'),x.get('hands')]==[y.get('farmer'),y.get('hands')] for x,y in zip(ca[start:end],cb[start:end]));row[label]=n/(end-start)
   sims.append(row);pairwise.append(row)
  structures=Counter('/'.join(str(sum(t['kind']==k for t in p['maps'][-1])) for k in ['PASTURE','COOP']) for p in profiles)
  summaries.append(dict(**spec,n=5,cash_mean=st.mean(p['reward'] for p in profiles),mixes=dict(mixes),structures=dict(structures),exact_topology_variants=len(signatures),dominant_topology_n=max(signatures.values()),escapes=sum(len(p['ledger']['animal_escapes']) for p in profiles),cash_errors=sum(p['ledger']['cash_parity_errors'] for p in profiles),route_similarity={k:st.mean(r[k] for r in sims) for k in ['D1_11','D12_19','D20_30']}))
  for day in [1,7,11,12,20,30]:
   counts=Counter((t['x'],t['y'],t['kind'],t['animal']) for p in profiles for t in p['maps'][day-1] if t['kind'] in ['PASTURE','COOP'])
   for (x,y,kind,animal),n in counts.items():recurrences.append(dict(submission=sid,day=day,x=x,y=y,kind=kind,animal=animal,n=n,total=5))
 for g in ps:
  meta=g['meta'];p=g['profile'];sid=meta['submission'];eid=meta['episode']
  for r in p['routes']:routecsv.append(dict(submission=sid,episode=eid,**{k:r[k] for k in ['day','hour','worker','x','y']},command=json.dumps(r['command'])))
  for e in p['transitions']:
   if e['command'][0]=='PLACE' and len(e['command'])>1 and e['command'][1] in ['COW','SHEEP','GOOSE']:placementcsv.append(dict(submission=sid,episode=eid,day=e['day'],hour=e['hour'],worker=e['worker'],x=e['x'],y=e['y'],animal=e['animal']))
  atlas.append(dict(submission=sid,episode=eid,score=meta['score'],cash=p['reward'],maps=p['maps'],routes=[[r['day'],r['hour'],r['worker'],r['x'],r['y'],r['command']] for r in p['routes']],harvest=p['harvest_events']))
 patterns=[]
 for sid in [s['submission'] for s in summaries]:
  seen=Counter()
  for g in [p for p in ps if p['meta']['submission']==sid]:
   seen.update(set((e['x'],e['y'],e['day'],e['hour'],e['animal']) for e in g['profile']['transitions'] if e['command'][0]=='PLACE' and len(e['command'])>1 and e['command'][1] in ['COW','SHEEP','GOOSE']))
  for (x,y,day,hour,animal),n in seen.items():
   if n>=3:patterns.append(dict(submission=sid,x=x,y=y,day=day,hour=hour,animal=animal,n=n,total=5))
 summary=dict(submissions=summaries,placement_patterns=patterns,topology_recurrence=recurrences,within_submission_action_similarity=pairwise,scope='Observed states and recorded actions only; repetitions do not establish optimality or reveal internal code. Final livestock counts include the effects of losses and replacement.')
 (OUT/'SUMMARY.json').write_text(json.dumps(summary,indent=2));(OUT/'ATLAS_DATA.json').write_text(json.dumps(atlas,separators=(',',':')))
 for name,rs in [('ROUTES.csv',routecsv),('PLACEMENTS.csv',placementcsv),('TOPOLOGY_RECURRENCE.csv',recurrences)]:
  with (OUT/name).open('w',newline='',encoding='utf-8') as f:w=csv.DictWriter(f,fieldnames=list(rs[0]));w.writeheader();w.writerows(rs)
 md='# Top 2750–3000 — topologie e traiettorie, 14 settembre 2026\n\nCinque submission distribuite nella fascia di score richiesta; cinque ultimi replay competitivi completi ciascuna, senza filtro per esito o topologia. 25 replay-lato, audit cassa superato. Score della classifica al momento della selezione, non rating garantito nei singoli incontri. Identificativi numerici; nessun codice dei competitor recuperato.\n\n| Submission | Score selezione | Mix finali C/S/G (frequenza) | Strutture pascoli/pollai (frequenza) | Fughe totali | Similarità comandi D1–11 | D12–19 | D20–30 |\n|---|---:|---|---|---:|---:|---:|---:|\n'
 for s in summaries:md+=f"| {s['submission']} | {s['score']} | {s['mixes']} | {s['structures']} | {s['escapes']} | {s['route_similarity']['D1_11']:.1%} | {s['route_similarity']['D12_19']:.1%} | {s['route_similarity']['D20_30']:.1%} |\n"
 md+='\nLa similarità è la quota media di batch con tutti i comandi dei lavoratori identici nelle 10 coppie di replay della stessa submission. Non significa identità del codice; la mappa interattiva mostra le posizioni realmente osservate prima delle azioni.\n\n## Ricorrenze utili\n\n- **56220723, score 2814,1:** struttura più regolare del campione, 14 pascoli e 4 pollai in 5/5; tre pollai Q0 nelle coordinate (4,1), (3,2), (2,3) e un pollaio vuoto in (3,7). Mix 9C5S3G in 3/5, 8C6S3G in 2/5, zero fughe. La variazione principale fra questi mix riguarda (6,2), mucca oppure pecora. Non dedurre che il pollaio vuoto produca ricavi.\n- **56218579, score 2937,3:** famiglia affine, ma diversifica: 14 pascoli/4 pollai in 3/5, 17/1 e 23/1 negli altri due. Mix fino a 1C22S; cinque fughe nel campione.\n- **56212183, score 2750,9:** alterna oche e pecore nelle tre posizioni Q0; le consistenze finali sono influenzate anche da tre fughe e mancate collocazioni.\n- **56173067, score 2992:** strutture e mix molto variabili, 29 fughe; il punteggio elevato non certifica regolarità biologica né un mix finale da copiare.\n- **56204870, score 2875,1:** famiglia più espansiva e variabile, fino a 25 pascoli e tre pollai; 71 fughe in cinque replay. Va studiato il saldo fra ricavi, espansione e perdite, non soltanto il numero massimo di animali.\n\n## Collocamenti ripetuti in almeno 3/5 replay\n\n| Submission | Casella | Animale | Giorno/ora | Frequenza |\n|---|---|---|---|---|\n'
 for p in sorted(patterns,key=lambda p:(p['submission'],p['day'],p['hour'],p['x'],p['y'])):md+=f"| {p['submission']} | ({p['x']},{p['y']}) | {p['animal']} | D{p['day']} H{p['hour']} | {p['n']}/5 |\n"
 md+='\n## Prossima evoluzione: ipotesi da verificare\n\n1. Correggere prima il recupero da assunzioni/costruzioni mancate in E22.2, mantenendolo separato dalle scelte di mix.\n2. Confrontare con la famiglia 14 pascoli/3 pollai occupati: scelta della specie in (6,2) e servizio di raccolta/collocamento Q0. Il quarto pollaio vuoto è un costo o una scelta di percorso da spiegare, non un obiettivo.\n3. Misurare tempi di vendita, prezzi realizzati e sostituzioni degli animali nelle famiglie variabili. Non assumere che ogni variazione derivi da una regola ottimale o da una reazione ai prezzi: parte è perdita o insuccesso operativo.\n\nNessuna nuova strategia implementata. Il campione è esplorativo e non rappresenta tutta la fascia. I percorsi dettagliati sono osservazioni, non una ricostruzione del sorgente.\n\n[Atlante interattivo](REPORT.html) · [Tutte le traiettorie](ROUTES.csv) · [Collocamenti](PLACEMENTS.csv) · [Ricorrenze topologiche](TOPOLOGY_RECURRENCE.csv) · [Sintesi e similarità](SUMMARY.json) · [Catalogo e hash](COHORT.json) · [Protocollo](PROTOCOL.json) · [E22.2 vs E22.1, 22 KPI e prezzi](../external_e22_2_20260914/REPORT.html).\n'
 (OUT/'REPORT.md').write_text(md,encoding='utf-8')
 table='<div class="tablewrap"><table><tr><th>Submission</th><th>Score</th><th>Mix C/S/G</th><th>Pascoli/pollai</th><th>Fughe</th><th>Batch identici D1–11</th></tr>'
 for s in summaries:table+=f"<tr><td>{s['submission']}</td><td>{s['score']}</td><td>{html.escape(str(s['mixes']))}</td><td>{html.escape(str(s['structures']))}</td><td>{s['escapes']}</td><td>{s['route_similarity']['D1_11']:.1%}</td></tr>"
 body='<h1>Top 2750–3000 · topologie e traiettorie</h1><p>25 replay, cinque submission distribuite nella fascia. Cinque incontri consecutivi per ciascuna; tutti completi e con cassa riconciliata. Score congelati dalla classifica il 14 settembre 2026.</p>'+table+'</table></div><p class="note"><b>La ricorrenza più regolare è 14 pascoli / 4 pollai della submission 56220723 (5/5), con tre oche e un pollaio vuoto.</b> Il mix alterna 9C5S3G e 8C6S3G senza fughe. Gli altri riferimenti includono forte variabilità e perdite: non copiare i mix finali come se fossero obiettivi pianificati.</p><p><a href="REPORT.md">Analisi, ricorrenze e ipotesi</a> · <a href="ROUTES.csv">Percorsi CSV</a> · <a href="PLACEMENTS.csv">Collocamenti</a> · <a href="SUMMARY.json">Frequenze e similarità</a> · <a href="../external_e22_2_20260914/REPORT.html">E22.2 / E22.1: 22 KPI e prezzi</a></p><div class="toolbar"><label>Replay <select id="game">'+''.join(f'<option value="{i}">{g["submission"]} · {g["episode"]}</option>' for i,g in enumerate(atlas))+'</select></label><label>Giorno <input id="day" type="range" min="1" max="30" value="12"><output id="daylabel">12</output></label><label>Lavoratore <select id="worker"></select></label></div><p id="meta"></p><div class="grid"><section><h3>Mappa e percorso osservato</h3><svg id="map" viewBox="0 0 550 550" style="width:100%"></svg><p class="meta">Coordinate zero-based (x,y). Mappa al checkpoint H24; percorso del lavoratore durante il giorno, punti prima delle azioni. Il percorso può precedere la costruzione mostrata. C=mucca, S=pecora, G=oca; P=pascolo vuoto, H=pollaio vuoto. Campi verdi, strutture azzurre/arancio, infestanti grigie. Le frecce indicano l’ordine dei punti.</p></section><section><h3>Azioni orarie del lavoratore</h3><div class="tablewrap" id="route"></div></section></div><section><h3>Raccolte riuscite nel giorno selezionato</h3><div class="tablewrap" id="harvest"></div></section>'
 js=r'''
const data=JSON.parse(document.getElementById('atlas').textContent),ns='http://www.w3.org/2000/svg',gsel=document.getElementById('game'),dsel=document.getElementById('day'),wsel=document.getElementById('worker');function el(t,a={},text){const e=document.createElementNS(ns,t);for(const [k,v]of Object.entries(a))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}function table(id,heads,rows){const t=document.createElement('table');for(const [i,row]of [heads,...rows].entries()){const tr=document.createElement('tr');for(const val of row){const td=document.createElement(i?'td':'th');td.textContent=val;tr.append(td)}t.append(tr)}document.getElementById(id).replaceChildren(t)}
function refresh(reset=false){const g=data[+gsel.value],day=+dsel.value,rs=g.routes.filter(r=>r[0]===day),workers=[...new Set(rs.map(r=>r[2]))].sort((a,b)=>a-b),old=+wsel.value;if(reset||!workers.includes(old)||wsel.options.length!==workers.length){wsel.replaceChildren(...workers.map(w=>{const o=document.createElement('option');o.value=w;o.textContent=w===0?'0 · contadino':w+' · manovale';return o}));if(workers.includes(old))wsel.value=old}const w=+wsel.value,route=rs.filter(r=>r[2]===w),svg=document.getElementById('map');svg.replaceChildren();document.getElementById('daylabel').textContent=day;document.getElementById('meta').textContent='Submission '+g.submission+' · episodio '+g.episode+' · score selezione '+g.score+' · cassa finale '+g.cash+' · D'+day;
const defs=el('defs'),marker=el('marker',{id:'arrow',viewBox:'0 0 10 10',refX:8,refY:5,markerWidth:5,markerHeight:5,orient:'auto-start-reverse'});marker.append(el('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#aa2458'}));defs.append(marker);svg.append(defs);const tiles=new Map(g.maps[day-1].map(t=>[t.x+','+t.y,t]));for(let y=0;y<10;y++)for(let x=0;x<10;x++){const t=tiles.get(x+','+y),color=!t?'#fff':t.kind==='PASTURE'?'#c7e5f5':t.kind==='COOP'?'#ffe0b0':t.kind==='PLANT'?'#d2edc7':'#ddd';const r=el('rect',{x:35+x*48,y:25+y*48,width:46,height:46,fill:color,stroke:'#aebbc8'});r.append(el('title',{},'('+x+','+y+') '+JSON.stringify(t||'empty')));svg.append(r);let label=t?.animal?({COW:'C',SHEEP:'S',GOOSE:'G'}[t.animal]):t?.kind==='PASTURE'?'P':t?.kind==='COOP'?'H':t?.crop?.slice(0,2)||'';svg.append(el('text',{x:58+x*48,y:52+y*48,'text-anchor':'middle',fill:'#234'},label))}for(let i=0;i<10;i++){svg.append(el('text',{x:58+i*48,y:15,'text-anchor':'middle'},i));svg.append(el('text',{x:20,y:52+i*48,'text-anchor':'middle'},i))}
for(let i=1;i<route.length;i++){const a=route[i-1],b=route[i];if(a[3]!==b[3]||a[4]!==b[4])svg.append(el('line',{x1:58+a[3]*48,y1:48+a[4]*48,x2:58+b[3]*48,y2:48+b[4]*48,stroke:'#aa2458','stroke-width':2,opacity:.8,'marker-end':'url(#arrow)'}))}for(const r of route){const c=el('circle',{cx:58+r[3]*48,cy:48+r[4]*48,r:4,fill:'#aa2458'});c.append(el('title',{},'H'+r[1]+' '+JSON.stringify(r[5])));svg.append(c)}table('route',['Ora','Posizione','Comando'],route.map(r=>['H'+r[1],'('+r[3]+','+r[4]+')',JSON.stringify(r[5])]));table('harvest',['Ora','Lavoratore','Casella','Raccolto'],g.harvest.filter(e=>e.day===day).map(e=>['H'+e.hour,e.worker,'('+e.x+','+e.y+')',JSON.stringify(e.gain)]))}
gsel.addEventListener('change',()=>refresh(true));dsel.addEventListener('input',()=>refresh(true));wsel.addEventListener('change',()=>refresh());refresh(true);
'''
 page='<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Top 2750–3000 · atlante</title><style>'+CSS+'</style><main>'+body+'</main><script id="atlas" type="application/json">'+json.dumps(atlas,ensure_ascii=False).replace('</','<\\/')+'</script><script>'+js+'</script></html>'
 (OUT/'REPORT.html').write_text(page,encoding='utf-8')
 verify=dict(submissions=5,player_replays=25,unique_episodes=len({g['meta']['episode'] for g in ps}),cash_parity_errors=sum(s['cash_errors'] for s in summaries),route_rows=len(routecsv),placement_rows=len(placementcsv),selection_score_min=2750.9,selection_score_max=2992.0,new_simulations=0)
 assert verify['cash_parity_errors']==0
 (OUT/'VERIFICATION.json').write_text(json.dumps(verify,indent=2));print(json.dumps(verify))
if __name__=='__main__':main()
