from pathlib import Path
b=Path('docs/model_specs/codex/e19/tools')
s=(b/'daily_routes_770_v31.py').read_text(encoding='utf-8')
s=s.replace('if core.remaining<=6:', 'if core.day<25:')
s=s.replace('core.remaining<=6 and commands in', 'commands in')
s=s.replace("result.append((target,[['WATER']],3,1,'SERVICE'))", "result.append((target,[['WATER']],8,1,'SERVICE'))")
s=s.replace("result.append((target,[['FEED']],3,1,'SERVICE'))", "result.append((target,[['FEED']],8,1,'SERVICE'))")
(b/'daily_routes_770_v34.py').write_text(s,encoding='utf-8')
s=(b/'daily_route_scheduler_770_v31.py').read_text(encoding='utf-8').replace('daily_routes_770_v31','daily_routes_770_v34').replace('(9*int(priority==7)', '(12*int(priority==8)+9*int(priority==7)')
(b/'daily_route_dispatch_770_v34.py').write_text(s,encoding='utf-8')
s=(b/'daily_route_scheduler_770_v33.py').read_text(encoding='utf-8').replace('daily_route_scheduler_770_v31','daily_route_dispatch_770_v34').replace('daily_routes_770_v31','daily_routes_770_v34')
(b/'daily_route_scheduler_770_v34.py').write_text(s,encoding='utf-8')
s=(b/'run_daily_routes_770_v33.py').read_text(encoding='utf-8').replace('_v33','_v34').replace('daily_routes_770_v31','daily_routes_770_v34').replace('daily_route_scheduler_770_v31','daily_route_dispatch_770_v34')
s=s.replace('V26 planned harvest deadlines','V34 early biological deadlines')
(b/'run_daily_routes_770_v34.py').write_text(s,encoding='utf-8')
